name: Publish
on:
  push:
    tags:
      - 'v*.*.*' 
  workflow_dispatch: 
    inputs: 
      version:
        type: string
        required: true
        description: 0.1.0
env: 
  IMAGE_NAME: gha-image
jobs: 
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        
      # バージョン設定
      - name: Set version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            # タグから'v'を削除してバージョン取得
            VERSION=${GITHUB_REF#refs/tags/v}
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          else
            # 手動実行の場合は入力されたバージョンを使用
            echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
          fi
          
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: docker/metadata-action@v5
        id: meta
        with: 
          images: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},value=${{ inputs.version }}
            type=raw,value=latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            
      - uses: docker/build-push-action@v5
        with: 
          push: true
          context: docker/example
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
    
